apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-gateway.fullname" . }}
  labels:
    {{- include "k8s-gateway.labels" . | nindent 4 }}
    {{- if .Values.customLabels }}
    {{ toYaml .Values.customLabels | trim | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8s-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-gateway.labels" . | nindent 8 }}
        {{- if .Values.customLabels }}
        {{ toYaml .Values.customLabels | trim | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ toYaml .Values | sha256sum }}
    spec:
      serviceAccountName: {{ include "k8s-gateway.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{- if .Values.image.registry }}{{ .Values.image.registry }}/{{- end }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: [ "-conf", "/etc/coredns/Corefile" ]
        {{- if .Values.secure }}
        securityContext:
          runAsUser: 1000
        {{- end }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        ports:
        - containerPort: 1053
          name: dns-udp
          protocol: UDP
        {{- if (eq .Values.service.useTcp true) }}
        - containerPort: 1053
          name: dns-tcp
          protocol: TCP
        {{- end }}
        {{- range .Values.extraZonePlugins | uniq }}
        {{- if eq .name "prometheus" }}
        - containerPort: {{ .parameters | regexFind "[^\\:]*$" }}
          name: metrics
          protocol: TCP
        {{- end }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "k8s-gateway.fullname" . }}
            items:
            - key: Corefile
              path: Corefile
            {{- range .Values.zoneFiles }}
            - key: {{ .filename }}
              path: {{ .filename }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
